---
name: Docker Image CI

on: [push]

env:
  DOCKER_IMAGE: devops-cop-container-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Dockerfile with Hadolint
        uses: brpaz/hadolint-action@v1.0.2

      - name: Build the Docker image
        run: docker build . -t $DOCKER_IMAGE:$GITHUB_SHA

      - name: Lint Docker image with Dockle
        run: bash scripts/dockle_wrapper.sh

      - name: Scan Docker Image for vulnerabilities with Trivy
        run: bash scripts/trivy_wrapper.sh || echo 'see https://github.com/aquasecurity/trivy/issues/198' # yamllint disable-line
        #        uses: homoluctus/gitrivy@v1
        #        with:
        #          image: $DOCKER_IMAGE:$GITHUB_SHA
        #          severity: CRITICAL
        #          ignore_unfixed: true
