---
name: Docker Image CI

on: [push]

env:
  IMAGE_TAG: devops-cop-container-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint Dockerfile with Hadolint
        uses: brpaz/hadolint-action@v1.0.2

      - name: Build the Docker image
        run: docker build . -t $IMAGE_TAG

      - name: Lint Docker image with Dockle
        run: bash scripts/dockle_wrapper.sh -t $IMAGE_TAG

      - name: Scan Docker Image for vulnerabilities with Trivy
        run: bash scripts/trivy_wrapper.sh -t $IMAGE_TAG
